# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "03fbd0683fd0d0395abd25ef030a8f38"
name = "Apex mart wholesale "
application_url = "https://apexmartwholesale.com/api/shopify/gdpr/customers/redact"
embedded = true

[webhooks]
api_version = "2025-10"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://apexmartwholesale.com/api/shopify/gdpr/customers/redact"
  customer_data_request_url = "https://apexmartwholesale.com/api/shopify/gdpr/customers/data_request"
  shop_deletion_url = "https://apexmartwholesale.com/api/shopify/gdpr/shop/redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_companies,customer_read_customers,customer_read_draft_orders,customer_read_markets,customer_read_metaobjects,customer_read_orders,customer_read_quick_sale,customer_read_store_credit_account_transactions,customer_read_store_credit_accounts,customer_write_companies,customer_write_customers,customer_write_orders,customer_write_quick_sale,read_all_cart_transforms,read_analytics,read_app_proxy,read_assigned_fulfillment_orders,read_audit_events,read_cart_transforms,read_cash_tracking,read_channels,read_checkout_branding_settings,read_checkouts,read_companies,read_content,read_custom_fulfillment_services,read_custom_pixels,read_customer_data_erasure,read_customer_events,read_customer_merge,read_customers,read_delivery_customizations,read_delivery_option_generators,read_discounts,read_discounts_allocator_functions,read_discovery,read_draft_orders,read_files,read_fulfillment_constraint_rules,read_fulfillments,read_gift_card_transactions,read_gift_cards,read_inventory,read_inventory_shipments,read_inventory_shipments_received_items,read_inventory_transfers,read_legal_policies,read_locales,read_locations,read_marketing_events,read_marketing_integrated_campaigns,read_markets,read_markets_home,read_merchant_managed_fulfillment_orders,read_metaobject_definitions,read_metaobjects,read_online_store_navigation,read_online_store_pages,read_order_edits,read_orders,read_packing_slip_templates,read_payment_customizations,read_payment_terms,read_pixels,read_price_rules,read_privacy_settings,read_product_feeds,read_product_listings,read_products,read_publications,read_purchase_options,read_reports,read_resource_feedbacks,read_returns,read_script_tags,read_shipping,read_shopify_payments_accounts,read_shopify_payments_bank_accounts,read_shopify_payments_disputes,read_shopify_payments_payouts,read_shopify_payments_provider_accounts_sensitive,read_store_credit_account_transactions,read_store_credit_accounts,read_themes,read_third_party_fulfillment_orders,read_translations,read_validations,unauthenticated_read_bulk_operations,unauthenticated_read_bundles,unauthenticated_read_checkouts,unauthenticated_read_content,unauthenticated_read_customer_tags,unauthenticated_read_customers,unauthenticated_read_metaobjects,unauthenticated_read_product_inventory,unauthenticated_read_product_listings,unauthenticated_read_product_pickup_locations,unauthenticated_read_product_tags,unauthenticated_read_selling_plans,unauthenticated_read_shop_pay_installments_pricing,unauthenticated_write_bulk_operations,unauthenticated_write_checkouts,unauthenticated_write_customers,write_app_proxy,write_assigned_fulfillment_orders,write_cart_transforms,write_channels,write_checkout_branding_settings,write_checkouts,write_companies,write_content,write_custom_fulfillment_services,write_custom_pixels,write_customer_data_erasure,write_customer_merge,write_customers,write_delivery_customizations,write_delivery_option_generators,write_discounts,write_discounts_allocator_functions,write_discovery,write_draft_orders,write_files,write_fulfillment_constraint_rules,write_fulfillments,write_gift_card_transactions,write_gift_cards,write_inventory,write_inventory_shipments,write_inventory_shipments_received_items,write_inventory_transfers,write_legal_policies,write_locales,write_locations,write_marketing_events,write_marketing_integrated_campaigns,write_markets,write_markets_home,write_merchant_managed_fulfillment_orders,write_metaobject_definitions,write_metaobjects,write_online_store_navigation,write_online_store_pages,write_order_edits,write_orders,write_packing_slip_templates,write_payment_customizations,write_payment_terms,write_pixels,write_price_rules,write_privacy_settings,write_product_feeds,write_product_listings,write_products,write_publications,write_purchase_options,write_reports,write_resource_feedbacks,write_returns,write_script_tags,write_shipping,write_shopify_payments_disputes,write_store_credit_account_transactions,write_theme_code,write_themes,write_third_party_fulfillment_orders,write_translations,write_validations"
optional_scopes = [
  "read_analytics",
  "read_app_proxy",
  "write_app_proxy",
  "read_assigned_fulfillment_orders",
  "write_assigned_fulfillment_orders",
  "read_audit_events",
  "read_customer_events",
  "read_cart_transforms",
  "write_cart_transforms",
  "read_all_cart_transforms",
  "read_validations",
  "write_validations",
  "read_cash_tracking",
  "read_channels",
  "write_channels",
  "read_checkout_branding_settings",
  "write_checkout_branding_settings",
  "write_checkouts",
  "read_checkouts",
  "read_companies",
  "write_companies",
  "read_custom_fulfillment_services",
  "write_custom_fulfillment_services",
  "read_custom_pixels",
  "write_custom_pixels",
  "read_customers",
  "write_customers",
  "read_customer_data_erasure",
  "write_customer_data_erasure",
  "read_customer_merge",
  "write_customer_merge",
  "read_delivery_customizations",
  "write_delivery_customizations",
  "read_price_rules",
  "write_price_rules",
  "read_discounts",
  "write_discounts",
  "read_discounts_allocator_functions",
  "write_discounts_allocator_functions",
  "read_discovery",
  "write_discovery",
  "write_draft_orders",
  "read_draft_orders",
  "read_files",
  "write_files",
  "read_fulfillment_constraint_rules",
  "write_fulfillment_constraint_rules",
  "read_fulfillments",
  "write_fulfillments",
  "read_gift_card_transactions",
  "write_gift_card_transactions",
  "read_gift_cards",
  "write_gift_cards",
  "write_inventory",
  "read_inventory",
  "write_inventory_shipments",
  "read_inventory_shipments",
  "write_inventory_shipments_received_items",
  "read_inventory_shipments_received_items",
  "write_inventory_transfers",
  "read_inventory_transfers",
  "read_legal_policies",
  "write_legal_policies",
  "read_delivery_option_generators",
  "write_delivery_option_generators",
  "read_locales",
  "write_locales",
  "write_locations",
  "read_locations",
  "read_marketing_integrated_campaigns",
  "write_marketing_integrated_campaigns",
  "write_marketing_events",
  "read_marketing_events",
  "read_markets",
  "write_markets",
  "read_markets_home",
  "write_markets_home",
  "read_merchant_managed_fulfillment_orders",
  "write_merchant_managed_fulfillment_orders",
  "read_metaobject_definitions",
  "write_metaobject_definitions",
  "read_metaobjects",
  "write_metaobjects",
  "read_online_store_navigation",
  "write_online_store_navigation",
  "read_online_store_pages",
  "write_online_store_pages",
  "write_order_edits",
  "read_order_edits",
  "read_orders",
  "write_orders",
  "write_packing_slip_templates",
  "read_packing_slip_templates",
  "read_payment_terms",
  "write_payment_terms",
  "read_payment_customizations",
  "write_payment_customizations",
  "read_pixels",
  "write_pixels",
  "read_privacy_settings",
  "write_privacy_settings",
  "read_product_feeds",
  "write_product_feeds",
  "read_product_listings",
  "write_product_listings",
  "read_products",
  "write_products",
  "read_publications",
  "write_publications",
  "read_purchase_options",
  "write_purchase_options",
  "write_reports",
  "read_reports",
  "read_resource_feedbacks",
  "write_resource_feedbacks",
  "read_returns",
  "write_returns",
  "read_script_tags",
  "write_script_tags",
  "read_shopify_payments_provider_accounts_sensitive",
  "read_shipping",
  "write_shipping",
  "read_shopify_payments_accounts",
  "read_shopify_payments_payouts",
  "read_shopify_payments_bank_accounts",
  "read_shopify_payments_disputes",
  "write_shopify_payments_disputes",
  "read_content",
  "write_content",
  "read_store_credit_account_transactions",
  "write_store_credit_account_transactions",
  "read_store_credit_accounts",
  "write_theme_code",
  "read_themes",
  "write_themes",
  "read_third_party_fulfillment_orders",
  "write_third_party_fulfillment_orders",
  "read_translations",
  "write_translations",
  "customer_read_companies",
  "customer_write_companies",
  "customer_write_customers",
  "customer_read_customers",
  "customer_read_draft_orders",
  "customer_read_markets",
  "customer_read_metaobjects",
  "customer_read_orders",
  "customer_write_orders",
  "customer_read_quick_sale",
  "customer_write_quick_sale",
  "customer_read_store_credit_account_transactions",
  "customer_read_store_credit_accounts",
  "unauthenticated_write_bulk_operations",
  "unauthenticated_read_bulk_operations",
  "unauthenticated_read_bundles",
  "unauthenticated_write_checkouts",
  "unauthenticated_read_checkouts",
  "unauthenticated_write_customers",
  "unauthenticated_read_customers",
  "unauthenticated_read_customer_tags",
  "unauthenticated_read_metaobjects",
  "unauthenticated_read_product_pickup_locations",
  "unauthenticated_read_product_inventory",
  "unauthenticated_read_product_listings",
  "unauthenticated_read_product_tags",
  "unauthenticated_read_selling_plans",
  "unauthenticated_read_shop_pay_installments_pricing",
  "unauthenticated_read_content"
]
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://apexmartwholesale.com/api/shopify/install",
  "https://apexmartwholesale.com/api/shopify/oauth/callback"
]

[app_preferences]
url = "https://apexmartwholesale.com"
